
import { GradeLevel, Resource, ResourceStatus, ResourceType, Subject, User, UserRole, UserStatus, Category, Review } from "./types";

export const MOCK_RESOURCES: Resource[] = [
  {
    id: "1",
    title: "Tổng hợp công thức Toán 12 - Giải tích",
    description: "Tài liệu tóm tắt đầy đủ các công thức giải tích lớp 12, bao gồm đạo hàm, nguyên hàm, tích phân và số phức. Phù hợp cho ôn thi THPT Quốc gia.",
    subject: Subject.Math,
    grade: GradeLevel.Grade12,
    type: ResourceType.PDF,
    author: "Thầy Nguyễn Văn A",
    date: "2023-10-15",
    views: 12500,
    downloads: 3400,
    thumbnailUrl: "https://picsum.photos/400/300?random=1",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Giải tích", "Ôn thi THPT", "Toán 12"],
    status: ResourceStatus.Approved,
    avgRating: 4.8,
    reviewCount: 124
  },
  {
    id: "2",
    title: "Bài giảng Vật Lý 11 - Điện tích Điện trường",
    description: "Video bài giảng chi tiết về định luật Coulomb và thuyết electron. Giải thích các hiện tượng thực tế và bài tập áp dụng.",
    subject: Subject.Physics,
    grade: GradeLevel.Grade11,
    type: ResourceType.Video,
    author: "Cô Lê Thị B",
    date: "2023-11-02",
    views: 8900,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=2",
    contentUrl: "https://www.youtube.com/embed/g2d578yvV9I", 
    tags: ["Điện học", "Vật lý 11", "Video"],
    status: ResourceStatus.Approved,
    avgRating: 4.5,
    reviewCount: 85
  },
  {
    id: "3",
    title: "Bộ đề trắc nghiệm Hóa học hữu cơ",
    description: "Ngân hàng 500 câu hỏi trắc nghiệm Hóa học hữu cơ từ cơ bản đến nâng cao, có đáp án chi tiết và hướng dẫn giải.",
    subject: Subject.Chemistry,
    grade: GradeLevel.Grade12,
    type: ResourceType.Quiz,
    author: "Thầy Trần C",
    date: "2023-09-20",
    views: 15600,
    downloads: 5200,
    thumbnailUrl: "https://picsum.photos/400/300?random=3",
    tags: ["Hóa hữu cơ", "Trắc nghiệm", "Luyện đề"],
    status: ResourceStatus.Approved,
    avgRating: 4.9,
    reviewCount: 210
  },
  {
    id: "4",
    title: "Phân tích bài thơ Tây Tiến",
    description: "Slide bài giảng phân tích chi tiết bài thơ Tây Tiến của Quang Dũng. Hình ảnh minh họa sinh động, sơ đồ tư duy dễ nhớ.",
    subject: Subject.Literature,
    grade: GradeLevel.Grade12,
    type: ResourceType.Lesson,
    author: "Cô Phạm D",
    date: "2023-12-05",
    views: 6700,
    downloads: 2100,
    thumbnailUrl: "https://picsum.photos/400/300?random=4",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Văn học", "Thơ", "Tây Tiến"],
    status: ResourceStatus.Approved,
    avgRating: 4.2,
    reviewCount: 45
  },
  {
    id: "5",
    title: "Lập trình Python cơ bản cho người mới bắt đầu",
    description: "Giáo trình nhập môn lập trình Python. Cấu trúc dữ liệu, vòng lặp, hàm và hướng đối tượng cơ bản.",
    subject: Subject.IT,
    grade: GradeLevel.Grade10,
    type: ResourceType.PDF,
    author: "Tech Academy",
    date: "2024-01-10",
    views: 22000,
    downloads: 8900,
    thumbnailUrl: "https://picsum.photos/400/300?random=5",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Python", "Lập trình", "Tin học 10"],
    status: ResourceStatus.Approved,
    avgRating: 4.7,
    reviewCount: 320
  },
  {
    id: "6",
    title: "Lịch sử thế giới hiện đại - Chiến tranh lạnh",
    description: "Tài liệu tổng hợp các sự kiện chính trong thời kỳ chiến tranh lạnh. Phân tích nguyên nhân và hậu quả.",
    subject: Subject.History,
    grade: GradeLevel.Grade12,
    type: ResourceType.PDF,
    author: "Thầy Sử E",
    date: "2023-10-30",
    views: 4500,
    downloads: 1200,
    thumbnailUrl: "https://picsum.photos/400/300?random=6",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Lịch sử 12", "Chiến tranh lạnh"],
    status: ResourceStatus.Approved,
    avgRating: 4.0,
    reviewCount: 22
  },
  {
    id: "7",
    title: "Grammar 101: Các thì trong Tiếng Anh",
    description: "Video hướng dẫn chi tiết cách sử dụng 12 thì trong tiếng Anh, kèm ví dụ minh họa và bài tập thực hành.",
    subject: Subject.English,
    grade: GradeLevel.General,
    type: ResourceType.Video,
    author: "Ms. Jennifer",
    date: "2024-02-15",
    views: 18900,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=7",
    contentUrl: "https://www.youtube.com/embed/L9AWrJnhsRI",
    tags: ["Tiếng Anh", "Ngữ pháp", "Cơ bản"],
    status: ResourceStatus.Approved,
    avgRating: 4.6,
    reviewCount: 150
  },
  {
    id: "8",
    title: "Hình học không gian 11: Quan hệ vuông góc",
    description: "Chuyên đề hình học không gian lớp 11, tập trung vào đường thẳng vuông góc với mặt phẳng và hai mặt phẳng vuông góc.",
    subject: Subject.Math,
    grade: GradeLevel.Grade11,
    type: ResourceType.PDF,
    author: "Thầy Toán Học",
    date: "2023-11-20",
    views: 5600,
    downloads: 1500,
    thumbnailUrl: "https://picsum.photos/400/300?random=8",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Hình học", "Toán 11", "Vuông góc"],
    status: ResourceStatus.Approved,
    avgRating: 4.3,
    reviewCount: 38
  },
  {
    id: "9",
    title: "Đề thi thử THPT Quốc gia 2024 môn Vật Lý",
    description: "Bộ đề thi thử sát với cấu trúc đề minh họa của Bộ GD&ĐT, có đáp án và lời giải chi tiết.",
    subject: Subject.Physics,
    grade: GradeLevel.Grade12,
    type: ResourceType.Quiz,
    author: "Tuyensinh247",
    date: "2024-03-01",
    views: 32000,
    downloads: 12000,
    thumbnailUrl: "https://picsum.photos/400/300?random=9",
    tags: ["Luyện đề", "Vật lý 12", "THPTQG"],
    status: ResourceStatus.Approved,
    avgRating: 4.9,
    reviewCount: 450
  },
  {
    id: "10",
    title: "Sơ đồ tư duy Văn học Việt Nam 1945-1975",
    description: "Hệ thống hóa kiến thức văn học giai đoạn kháng chiến chống Pháp và Mỹ bằng sơ đồ tư duy trực quan.",
    subject: Subject.Literature,
    grade: GradeLevel.Grade12,
    type: ResourceType.PDF,
    author: "Học Văn Cô Sương",
    date: "2023-12-12",
    views: 9800,
    downloads: 4500,
    thumbnailUrl: "https://picsum.photos/400/300?random=10",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Văn học", "Mindmap", "Ôn thi"],
    status: ResourceStatus.Approved,
    avgRating: 4.7,
    reviewCount: 90
  },
  {
    id: "11",
    title: "Hóa học 10: Cấu tạo nguyên tử",
    description: "Bài giảng về các hạt cơ bản, hạt nhân nguyên tử, nguyên tố hóa học và đồng vị.",
    subject: Subject.Chemistry,
    grade: GradeLevel.Grade10,
    type: ResourceType.Lesson,
    author: "Thầy Hóa",
    date: "2023-09-10",
    views: 4200,
    downloads: 1100,
    thumbnailUrl: "https://picsum.photos/400/300?random=11",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Hóa 10", "Nguyên tử"],
    status: ResourceStatus.Approved,
    avgRating: 4.1,
    reviewCount: 15
  },
  {
    id: "12",
    title: "IELTS Speaking Part 2: Describe a person",
    description: "Hướng dẫn trả lời các dạng đề miêu tả người trong phần thi nói IELTS. Cung cấp từ vựng và cấu trúc câu hay.",
    subject: Subject.English,
    grade: GradeLevel.General,
    type: ResourceType.Video,
    author: "IELTS Fighter",
    date: "2024-01-25",
    views: 15600,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=12",
    contentUrl: "https://www.youtube.com/embed/dummy",
    tags: ["IELTS", "Speaking", "Tiếng Anh"],
    status: ResourceStatus.Approved,
    avgRating: 4.8,
    reviewCount: 110
  },
  {
    id: "13",
    title: "Lịch sử Việt Nam: Triều đại nhà Lý",
    description: "Tìm hiểu về sự ra đời và phát triển của nhà Lý, dời đô về Thăng Long và cuộc kháng chiến chống Tống.",
    subject: Subject.History,
    grade: GradeLevel.Grade10,
    type: ResourceType.PDF,
    author: "Sử Địa Vui",
    date: "2023-10-05",
    views: 3400,
    downloads: 800,
    thumbnailUrl: "https://picsum.photos/400/300?random=13",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Lịch sử 10", "Trung đại"],
    status: ResourceStatus.Approved,
    avgRating: 4.0,
    reviewCount: 12
  },
  {
    id: "14",
    title: "C++: Cấu trúc dữ liệu và giải thuật",
    description: "Giới thiệu về mảng, danh sách liên kết, ngăn xếp, hàng đợi và các thuật toán sắp xếp cơ bản.",
    subject: Subject.IT,
    grade: GradeLevel.University,
    type: ResourceType.Lesson,
    author: "CodeLearn",
    date: "2024-02-02",
    views: 28000,
    downloads: 6700,
    thumbnailUrl: "https://picsum.photos/400/300?random=14",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Lập trình", "C++", "DSA"],
    status: ResourceStatus.Approved,
    avgRating: 5.0,
    reviewCount: 310
  },
  {
    id: "15",
    title: "Toán 10: Vectơ và các phép toán",
    description: "Lý thuyết và bài tập về tổng, hiệu hai vectơ, tích của vectơ với một số.",
    subject: Subject.Math,
    grade: GradeLevel.Grade10,
    type: ResourceType.PDF,
    author: "Cô Lan Toán",
    date: "2023-09-15",
    views: 7800,
    downloads: 2300,
    thumbnailUrl: "https://picsum.photos/400/300?random=15",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Toán 10", "Hình học"],
    status: ResourceStatus.Approved,
    avgRating: 4.4,
    reviewCount: 56
  },
  {
    id: "16",
    title: "Vật lý hạt nhân và năng lượng",
    description: "Chuyên đề nâng cao về phản ứng hạt nhân, phóng xạ và ứng dụng năng lượng hạt nhân.",
    subject: Subject.Physics,
    grade: GradeLevel.Grade12,
    type: ResourceType.Lesson,
    author: "Vật Lý Hiện Đại",
    date: "2023-12-20",
    views: 5100,
    downloads: 1400,
    thumbnailUrl: "https://picsum.photos/400/300?random=16",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Vật lý 12", "Hạt nhân"],
    status: ResourceStatus.Approved,
    avgRating: 4.2,
    reviewCount: 28
  },
  {
    id: "17",
    title: "Hóa học 11: Sự điện li",
    description: "Bài tập trắc nghiệm về chất điện li mạnh, yếu, pH của dung dịch và phản ứng trao đổi ion.",
    subject: Subject.Chemistry,
    grade: GradeLevel.Grade11,
    type: ResourceType.Quiz,
    author: "Hóa Học 247",
    date: "2023-10-25",
    views: 8900,
    downloads: 3100,
    thumbnailUrl: "https://picsum.photos/400/300?random=17",
    tags: ["Hóa 11", "Trắc nghiệm"],
    status: ResourceStatus.Approved,
    avgRating: 4.6,
    reviewCount: 72
  },
  {
    id: "18",
    title: "Văn mẫu 12: Người lái đò Sông Đà",
    description: "Tuyển tập các bài văn hay phân tích hình tượng con sông Đà và người lái đò.",
    subject: Subject.Literature,
    grade: GradeLevel.Grade12,
    type: ResourceType.PDF,
    author: "Thư Viện Văn",
    date: "2024-01-05",
    views: 11200,
    downloads: 5600,
    thumbnailUrl: "https://picsum.photos/400/300?random=18",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Văn 12", "Nguyễn Tuân"],
    status: ResourceStatus.Approved,
    avgRating: 4.7,
    reviewCount: 140
  },
  {
    id: "19",
    title: "HTML & CSS: Thiết kế web căn bản",
    description: "Khóa học xây dựng giao diện website từ con số 0. Tìm hiểu về thẻ HTML, Flexbox và Grid trong CSS.",
    subject: Subject.IT,
    grade: GradeLevel.General,
    type: ResourceType.Video,
    author: "F8 Official",
    date: "2023-08-20",
    views: 45000,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=19",
    contentUrl: "https://www.youtube.com/embed/dummy",
    tags: ["Web Design", "HTML", "CSS"],
    status: ResourceStatus.Approved,
    avgRating: 5.0,
    reviewCount: 1500
  },
  {
    id: "20",
    title: "Lịch sử 11: Cách mạng tháng Mười Nga",
    description: "Nguyên nhân, diễn biến và ý nghĩa lịch sử của cuộc cách mạng tháng Mười Nga năm 1917.",
    subject: Subject.History,
    grade: GradeLevel.Grade11,
    type: ResourceType.PDF,
    author: "Thầy Minh Sử",
    date: "2023-11-10",
    views: 2900,
    downloads: 600,
    thumbnailUrl: "https://picsum.photos/400/300?random=20",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Lịch sử 11", "Thế giới"],
    status: ResourceStatus.Approved,
    avgRating: 4.0,
    reviewCount: 15
  },
  {
    id: "21",
    title: "Tiếng Anh giao tiếp công sở",
    description: "Các mẫu câu và tình huống giao tiếp thường gặp trong môi trường làm việc quốc tế.",
    subject: Subject.English,
    grade: GradeLevel.University,
    type: ResourceType.Lesson,
    author: "Langmaster",
    date: "2024-03-10",
    views: 9500,
    downloads: 2100,
    thumbnailUrl: "https://picsum.photos/400/300?random=21",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Giao tiếp", "Tiếng Anh", "Business"],
    status: ResourceStatus.Approved,
    avgRating: 4.5,
    reviewCount: 67
  },
  {
    id: "22",
    title: "Xác suất thống kê đại cương",
    description: "Giáo trình đại học môn Xác suất thống kê. Biến ngẫu nhiên, phân phối xác suất và kiểm định giả thuyết.",
    subject: Subject.Math,
    grade: GradeLevel.University,
    type: ResourceType.PDF,
    author: "ĐH Bách Khoa",
    date: "2023-09-01",
    views: 13400,
    downloads: 4500,
    thumbnailUrl: "https://picsum.photos/400/300?random=22",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Đại học", "Toán cao cấp"],
    status: ResourceStatus.Approved,
    avgRating: 4.3,
    reviewCount: 98
  },
  // Add some pending resources for testing admin approval
  {
    id: "23",
    title: "[Chờ Duyệt] Đề thi thử Toán 2024 Lần 1",
    description: "Đề thi thử trường THPT Chuyên KHTN, có đáp án chi tiết.",
    subject: Subject.Math,
    grade: GradeLevel.Grade12,
    type: ResourceType.PDF,
    author: "Người dùng A",
    date: "2024-03-20",
    views: 0,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=23",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Toán 12", "Đề thi thử"],
    status: ResourceStatus.Pending,
    avgRating: 0,
    reviewCount: 0
  },
  {
    id: "24",
    title: "[Chờ Duyệt] Tài liệu ôn tập Hóa 11 - Hydrocarbon",
    description: "Tổng hợp lý thuyết và bài tập về Ankan, Anken, Ankin.",
    subject: Subject.Chemistry,
    grade: GradeLevel.Grade11,
    type: ResourceType.PDF,
    author: "Người dùng B",
    date: "2024-03-21",
    views: 0,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=24",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Hóa 11", "Hữu cơ"],
    status: ResourceStatus.Pending,
    avgRating: 0,
    reviewCount: 0
  },
  // New resources for Grades 1-9
  {
    id: "25",
    title: "Toán lớp 1: Phép cộng trong phạm vi 10",
    description: "Bài giảng trực quan sinh động giúp bé làm quen với phép cộng cơ bản.",
    subject: Subject.Math,
    grade: GradeLevel.Grade1,
    type: ResourceType.Video,
    author: "Cô Lan Tiểu Học",
    date: "2024-01-15",
    views: 5600,
    downloads: 0,
    thumbnailUrl: "https://picsum.photos/400/300?random=25",
    contentUrl: "https://www.youtube.com/embed/dummy",
    tags: ["Toán 1", "Tiểu học"],
    status: ResourceStatus.Approved,
    avgRating: 5.0,
    reviewCount: 45
  },
  {
    id: "26",
    title: "Tiếng Việt 3: Tập làm văn",
    description: "Hướng dẫn viết đoạn văn kể về người thân. Mẫu câu và từ vựng gợi ý.",
    subject: Subject.Literature,
    grade: GradeLevel.Grade3,
    type: ResourceType.PDF,
    author: "Thầy Hùng",
    date: "2023-11-20",
    views: 3200,
    downloads: 1200,
    thumbnailUrl: "https://picsum.photos/400/300?random=26",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["Tiếng Việt 3", "Tập làm văn"],
    status: ResourceStatus.Approved,
    avgRating: 4.2,
    reviewCount: 18
  },
  {
    id: "27",
    title: "Khoa học tự nhiên 6: Trái đất và bầu trời",
    description: "Tìm hiểu về các hành tinh trong hệ mặt trời, chuyển động của Trái đất.",
    subject: Subject.Physics,
    grade: GradeLevel.Grade6,
    type: ResourceType.Lesson,
    author: "KHTN Vui",
    date: "2023-12-10",
    views: 4100,
    downloads: 900,
    thumbnailUrl: "https://picsum.photos/400/300?random=27",
    contentUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    tags: ["KHTN 6", "Địa lý"],
    status: ResourceStatus.Approved,
    avgRating: 4.5,
    reviewCount: 30
  },
  {
    id: "28",
    title: "Toán 9: Hệ thức lượng trong tam giác vuông",
    description: "Tổng hợp công thức và bài tập trắc nghiệm về hệ thức lượng.",
    subject: Subject.Math,
    grade: GradeLevel.Grade9,
    type: ResourceType.Quiz,
    author: "Toán Thầy Kiên",
    date: "2024-02-28",
    views: 8500,
    downloads: 2500,
    thumbnailUrl: "https://picsum.photos/400/300?random=28",
    tags: ["Toán 9", "Hình học", "Ôn thi vào 10"],
    status: ResourceStatus.Approved,
    avgRating: 4.8,
    reviewCount: 88
  }
];

export const MOCK_USERS: User[] = [
  {
    id: "admin-01",
    name: "Administrator",
    email: "admin@school.edu.vn",
    role: UserRole.Admin,
    joinDate: "2023-01-01",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin"
  },
  {
    id: "admin-02",
    name: "Quản trị viên Minh",
    email: "minhadmin@school.edu.vn",
    role: UserRole.Admin,
    joinDate: "2023-03-15",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=MinhAdmin"
  },
  {
    id: "1",
    name: "Nguyễn Văn An",
    email: "nguyenvana@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-08-15",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=An"
  },
  {
    id: "2",
    name: "Trần Thị Bình",
    email: "tranthib@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-09-01",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Binh"
  },
  {
    id: "3",
    name: "Lê Minh Cường",
    email: "leminhcuong@school.edu.vn",
    role: UserRole.User,
    joinDate: "2022-01-20",
    status: UserStatus.Inactive,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Cuong"
  },
  {
    id: "4",
    name: "Phạm Thu Hà",
    email: "phamthuha@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-11-10",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ha"
  },
  {
    id: "5",
    name: "Hoàng Văn Dũng",
    email: "hoangvandung@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-09-05",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dung"
  },
  {
    id: "6",
    name: "Vũ Thị Mai",
    email: "vuthimai@school.edu.vn",
    role: UserRole.User,
    joinDate: "2024-01-12",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mai"
  },
  {
    id: "7",
    name: "Đỗ Thanh Sơn",
    email: "dothanhson@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-12-01",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Son"
  },
  {
    id: "8",
    name: "Ngô Bảo Châu",
    email: "ngobaochau@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-05-20",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chau"
  },
  {
    id: "9",
    name: "Bùi Thị Xuân",
    email: "buithixuan@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-10-30",
    status: UserStatus.Inactive,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Xuan"
  },
  {
    id: "10",
    name: "Lý Thường Kiệt",
    email: "lythuongkiet@school.edu.vn",
    role: UserRole.User,
    joinDate: "2024-02-14",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kiet"
  },
  {
    id: "11",
    name: "Trần Hưng Đạo",
    email: "tranhungdao@school.edu.vn",
    role: UserRole.User,
    joinDate: "2024-01-05",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dao"
  },
  {
    id: "12",
    name: "Hồ Xuân Hương",
    email: "hoxuanhuong@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-07-22",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Huong"
  },
  {
    id: "13",
    name: "Nguyễn Du",
    email: "nguyendu@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-11-15",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Du"
  },
  {
    id: "14",
    name: "Đặng Thùy Trâm",
    email: "dangthuytram@school.edu.vn",
    role: UserRole.User,
    joinDate: "2023-09-12",
    status: UserStatus.Active,
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tram"
  }
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    resourceId: "1",
    userId: "1",
    userName: "Nguyễn Văn An",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=An",
    rating: 5,
    comment: "Tài liệu rất chi tiết và dễ hiểu. Cảm ơn thầy đã chia sẻ!",
    date: "2023-10-20"
  },
  {
    id: "rev-2",
    resourceId: "1",
    userId: "2",
    userName: "Trần Thị Bình",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Binh",
    rating: 4,
    comment: "Phần số phức hơi khó hiểu một chút, nhưng tổng thể rất tốt.",
    date: "2023-10-22"
  },
  {
    id: "rev-3",
    resourceId: "2",
    userId: "4",
    userName: "Phạm Thu Hà",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ha",
    rating: 5,
    comment: "Video bài giảng giọng cô rất hay và truyền cảm.",
    date: "2023-11-05"
  },
  {
    id: "rev-4",
    resourceId: "19",
    userId: "6",
    userName: "Vũ Thị Mai",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mai",
    rating: 5,
    comment: "Khóa học tuyệt vời nhất mình từng học. F8 mãi đỉnh!",
    date: "2023-08-25"
  }
];

// Generate Mock Categories from existing Enums
export const MOCK_CATEGORIES: Category[] = [
  // Subjects
  ...Object.values(Subject).map((s, i) => ({
    id: `subj-${i}`,
    name: s,
    type: 'SUBJECT' as const,
    description: `Tài liệu và bài giảng môn ${s}`,
    count: Math.floor(Math.random() * 100) + 10,
    status: 'Active' as const
  })),
  // Grades
  ...Object.values(GradeLevel).map((g, i) => ({
    id: `grade-${i}`,
    name: g,
    type: 'GRADE' as const,
    description: `Chương trình học và tài liệu ${g}`,
    count: Math.floor(Math.random() * 200) + 50,
    status: 'Active' as const
  })),
  // Resource Types
  ...Object.values(ResourceType).map((t, i) => ({
    id: `type-${i}`,
    name: t,
    type: 'RESOURCE_TYPE' as const,
    description: `Định dạng tài liệu ${t}`,
    count: Math.floor(Math.random() * 500) + 20,
    status: 'Active' as const
  }))
];